logging:
  level:
    root: INFO



spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: localhost
      port: 27017
      database: escuagest
      username: escuagest
      password: chancleta
