logging:
  level:
    root: INFO

spring:
  data:
    mongodb:
      auto-index-creation: true
      host: ${ESCUAGEST_MONGODB_HOST}
      port: ${ESCUAGEST_MONGODB_PORT}
      database: ${ESCUAGEST_MONGODB_DATABASE}
      username: ${ESCUAGEST_MONGODB_USERNAME}
      password: ${ESCUAGEST_MONGODB_PASSWORD}

springdoc:
  swagger-ui:
    url: /openapi.yml