openapi: 3.0.3
info:
  title: Escuagest API
  description: "Escuagest API"
  contact:
    email: javier.ote.ote@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080
tags:
  - name: user
    description: Operations about user
  - name: competition
  - name: sessions
  - name: race
paths:
  /users:
    get:
      summary: Get logged user info
      operationId: GetLoggedUser
      tags:
        - GetLoggedUser
        - user
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
  /competitions:
    get:
      summary: return all competitions
      operationId: GetAllCompetitions
      tags:
        - GetAllCompetitions
        - competition
        - sessions
        - race
      parameters:
        - in: query
          name: Pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        200:
          description: return a list of competitions
          content:
            application/json:
              schema:
                type: Page
    post:
      operationId: AddCompetition
      tags:
        - AddCompetition
        - competition
        - sessions
        - race
      requestBody:
        description: Body request to create a Competition
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitionDTO'
      responses:
        200:
          description: return a list of competitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionDTO'
    put:
      summary: full update of a competition,
      operationId: UpdateCompetition
      tags:
        - UpdateCompetition
        - competition
        - sessions
        - race
      requestBody:
        description: Body request to create a Competition
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompetitionDTO'
      responses:
        200:
          description: The competition updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionDTO'
  /competitions/{reference-id}:
    get:
      summary: Get a competition from a reference-id
      operationId: GetCompetitionsByReference
      tags:
        - GetCompetitionByIdReference
        - competition
        - sessions
        - race
      parameters:
        - in: path
          name: reference-id
          required: true
          schema:
            type: string
      responses:
        200:
          description: The competition selected with the reference
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionDTO'

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    InternalServerError:
      description: "Generic Internal Error"
      content:
        application/json:
          schema:
            $ref: '#components/schemas/InternalServerError'
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        fullname:
          type: string
        firstName:
          type: string
        lastsNames:
          type: string
        groups:
          type: array
          items:
            type: string
          uniqueItems: true
        emailVerified:
          type: boolean
        email:
          type: string
    CompetitionDTO:
      type: object
      required:
        - title
        - reference
        - inscriptionLimitDate
        - maxInscriptionsPerSwimmer
      properties:
        title:
          type: string
          maximum: 80
        reference:
          type: string
          pattern: ^[a-zA-Z0-9-_]{7,80}$
        description:
          type: string
        competitionDay:
          type: date
        inscriptionLimitDate:
          type: date-time
        maxInscriptionsPerSwimmer:
          type: integer
        location:
          type: string
        sessions:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SessionDTO'
    SessionDTO:
      type: object
      required:
        - date
        - name
      properties:
        date:
          type: date
        name:
          type: string
        races:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/RaceDTO'
    RaceDTO:
      required:
        - name
        - style
      properties:
        distance:
          type: integer
        style:
          type: string
          enum:
            - backstroke
            - freestyle
            - four_styles
            - breaststroke
    LinkDTO:
      properties:
        href:
          type: string
        name:
          type: string
    Pageable:
      type: pageable
    Page:
      type: page
    SortDirectionEnum:
      type: string
      enum:
        - DESC
        - ASC
    ErrorFields:
      properties:
        status:
          type: string
        title:
          type: string
        detail:
          type: string
        type:
          type: string
        traceId:
          type: string
    NotFoundError:
      description: Not found
      properties:
        status:
          type: string
          example: 404
        type:
          type: string
          example: NotFoundError
    ForbiddenError:
      description: Forbidden
      properties:
        status:
          type: string
          example: 404
        type:
          type: string
          example: ForbiddenError
    UnauthorizedError:
      description: Unauthorized
      properties:
        status:
          type: string
          example: 404
        type:
          type: string
          example: UnauthorizedError
    BadRequestError:
      description: Bad Request
      properties:
        status:
          type: string
          example: 404
        type:
          type: string
          example: BadRequestError
    InternalServerError:
      description: Internal Server Error
      properties:
        status:
          type: string
          example: 404
        type:
          type: string
          example: InternalServerError

security:
  - bearerAuth: []